samples: lz4: add frametest example
pull in frametest sample from lz4 project and adapt it to
compile for zephyr.

HACK:
/opt/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: /opt/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/
v7e-m/nofp/libc.a(libc_time_clock.c.o): in function `clock':
clock.c:(.text.clock+0x4): undefined reference to `times'
collect2: error: ld returned 1 exit status

usage of clock() is replaced/removed with time(NULL), as zephyr
doesn't have support for clock()

stat: in nrf52840dk
Memory region         Used Size  Region Size  %age Used
           FLASH:       93840 B         1 MB      8.95%
             RAM:       46784 B       256 KB     17.85%
        IDT_LIST:          0 GB        32 KB      0.00%

Signed-off-by: Parthiban Nallathambi <parthiban@linumiz.com>